model_list:
  - model_name: gemma4
    litellm_params:
      model: openai/gemma4
      api_base: https://api.nan.builders/v1
      api_key: os.environ/NAN_API_KEY

  - model_name: qwen3.6
    litellm_params:
      model: openai/qwen3.6
      api_base: https://api.nan.builders/v1
      api_key: os.environ/NAN_API_KEY

  - model_name: qwen3-embedding
    litellm_params:
      model: openai_like/qwen3-embedding
      api_base: https://api.nan.builders/v1
      api_key: os.environ/NAN_API_KEY
      extra_body:
        dimensions: 1536
        encoding_format: float
    model_info:
      mode: embedding

  - model_name: claude-opus-4-7
    litellm_params:
      model: openai/deepseek-v4-flash
      api_base: https://api.nan.builders/v1
      api_key: os.environ/NAN_API_KEY

  - model_name: claude-sonnet-4-6
    litellm_params:
      model: openai/qwen3.6
      api_base: https://api.nan.builders/v1
      api_key: os.environ/NAN_API_KEY

  - model_name: claude-haiku-4-5-20251001
    litellm_params:
      model: openai/gemma4
      api_base: https://api.nan.builders/v1
      api_key: os.environ/NAN_API_KEY

litellm_settings:
  drop_params: true

general_settings:
  master_key: os.environ/LITELLM_MASTER_KEY
